### ISSUE TITLE
怎么有如此无聊的库 !-_-

### ISSUE THREAD

**Issue by cocody** [W3cplus/SassMagic#11]
@mixin float($direction: left) { 
	float: unquote($direction);
 }

都是些什么鬼!-_-

**Comment by airen** [comment]
这个当初是没有想好，现在整个库也还在完善当中。

**Comment by cocody** [comment]
可以将每一个mixins function的功能,应用场景 都列出来:例如有一个
mixins: loopAnim()
场景: 可以帮你方便地做动画帧,等等

**Comment by airen** [comment]
是的，正在完善这方面的文档，后面的每个mixins和funcions都会有对应的示例



2016-09-12 18:08 GMT+08:00 cocody <notifications@github.com>:
