### ISSUE TITLE
functions中的_convert.scss问题

### ISSUE THREAD

**Issue by cklwblove** [W3cplus/SassMagic#18]
functions中的_convert.scss中的**px2em**方法中的单位应该是**em**吧

**Comment by richard-chen-1985** [comment]
我也发现了，并且提了PR，不过貌似大漠很忙，没时间解答

**Comment by airen** [comment]
@cklwblove @richard-chen-1985 这个functions已经进行过优化了。把以前几个功能合并到一个函数里了。
